### ISSUE TITLE
Links still not showing up in Reaviz.io 's Sankey Diagram

### ISSUE THREAD

**Issue by mbecuwe** [jask-oss/reaviz#102] opened 2019-10-24 08:38 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Links wont show up with basic example of sankey diagram using reaviz.io
![image](https://user-images.githubusercontent.com/31662467/67468080-304ee380-f64a-11e9-9625-60b3d01d22cd.png)

## Expected behavior

Expect links to show up

## Environment

<pre><code>
Libs:
- react version: X.Y.Z
- reaviz version: X.Y.Z

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mbecuwe** [comment] 2019-10-29 10:31
Thanks a lot it was background indeed

**Comment by amcdnl** [comment] 2019-10-29 13:36
I need to update the template for the sandboxes to have a dark background

**Comment by mbecuwe** [comment] 2019-10-29 15:02
That would be awesome, and I dont get why having white background implies we cannot see links anymore, thank you anyway

**Comment by mutsumiya** [comment] 2019-10-30 09:17
Hi @mbecuwe, the link issue was caused by the css `mix-blend-mode: screen` used in the SankeyLink.

It seems `mix-blend-mode: screen` doesn't work with white background, so the easiest way to workaround/fix the issue is to add `style={{ mixBlendMode: "unset" }}` to SankeyLink. For the details, I created [this demo](https://codesandbox.io/s/sankey-plot-simple-s2ty4?fontsize=14&module=%2Fexample.js), so please check how `mixBlendMode` is specified.

Let me mention that since reaviz's default color theme is made for dark background, the tooltip (especially the text and background color) needs to be adjusted to make it visible on white background. You can see how to customize the tooltip in the above demo too.

**Comment by mutsumiya** [comment] 2020-03-02 18:21
The background color has been updated to dark, so closing this as resolved.

**Closed by mutsumiya** 2020-03-02 18:21 UTC
